# Generated by Django 6.0.4 on 2026-05-02 15:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_menuitem_rating_menuitem_review_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='MissedCall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=20)),
                ('call_sid', models.CharField(blank=True, max_length=100)),
                ('call_status', models.CharField(default='failed', max_length=50)),
                ('reason', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved', models.BooleanField(default=False)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='missed_calls', to='api.order')),
                ('waiter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='missed_calls', to='api.waiter')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
